// netlify/functions/heatmap.mjs
//
// Read endpoint for the /heatmap surface — a market-cap-weighted GICS-
// sector treemap of every S&P 500 constituent, colored by the most-
// recent-session percent change. Joins three pieces of state at
// request time:
//
//   1. The static SPX roster shipped at src/data/sp500-roster.json,
//      generated by scripts/backfill/sp500-roster.mjs from the SSGA
//      SPY holdings file plus the GitHub datasets/s-and-p-500-companies
//      CSV. Provides ticker, name, market-cap weight, GICS sector,
//      GICS sub-industry. The function reads it once per cold start.
//
//   2. Massive's grouped daily bars at
//      /v2/aggs/grouped/locale/us/market/stocks/{date} — one call
//      returns OHLC for every US ticker on a specific trading date.
//      Two calls (most-recent trading day with data + the day before
//      that) give us close-to-close percent change for every name in
//      one pair of round trips. This requires the Stocks product on
//      the Massive subscription (the existing MASSIVE_API_KEY was
//      provisioned for Options per ingest-background.mjs and got the
//      Stocks Starter add-on later). On 401/403/timeout the function
//      falls back to public.daily_eod's 15 SPDR sector ETFs.
//
// Date-keyed grouped bars are used in preference to the snapshot
// endpoint because of how the snapshot's "today" semantics behave on
// off-hours / weekends — on a Saturday the snapshot treats the
// not-yet-started Monday session as today, returning empty `day`
// and `lastTrade` fields with Friday's close in `prevDay`, so
// `todaysChangePerc` is 0 across every ticker. The grouped endpoint
// is unambiguous: "give me Friday's bars" returns Friday's bars
// regardless of when the request fires. This makes the weekend
// experience honest (every tile shows Friday's actual session
// move vs Thursday's close) and the intraday experience identical
// (the most-recent bar is the in-progress current-day bar with a
// running close that updates as Massive ingests trades).
//
// Storage and memory are deliberately not in scope for this surface —
// per the design ask, we only need each constituent's most-recent
// close + the close before that. No Supabase write path, no daily
// backfill, no historical time series. The roster JSON is the only
// persisted artifact and it only changes when SP500 membership or
// weights drift materially.
//
// Cache profile mirrors the cadence of the underlying data:
//   Market hours (09:30-16:00 ET, weekdays):  max-age=60, swr=300
//   Off-hours / weekends:                     max-age=900, swr=86400
// The off-hours cache is loose because the most-recent grouped bar
// stays settled until the next session opens; tightening it would
// only burn origin requests for no freshness gain.

import { readFileSync } from 'node:fs';

// Load the roster at function-module init so the JSON parse only
// happens once per cold start. Using readFileSync rather than an
// import-attributes JSON import (`with { type: 'json' }`) keeps this
// portable across Node 20 / 22 — the import-attributes syntax landed
// at different stability levels in each, and Netlify's function
// runtime defaults can lag the local Node version. The JSON's
// inclusion in the deploy bundle is guaranteed by the
// [functions.heatmap] included_files entry in netlify.toml; the
// bundler can't trace runtime fs reads automatically.
const ROSTER_URL = new URL('../../src/data/sp500-roster.json', import.meta.url);
const roster = JSON.parse(readFileSync(ROSTER_URL, 'utf8'));

const MASSIVE_API_KEY = process.env.MASSIVE_API_KEY;
const MASSIVE_BASE = 'https://api.massive.com';
const MASSIVE_TIMEOUT_MS = 10000;

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_KEY;
const SUPABASE_TIMEOUT_MS = 8000;

// Map of SPDR sector ETF → GICS sector name. When the Massive Stocks
// product is unavailable we fall back to the daily_eod table which
// only carries the 15-symbol rotations universe. The fallback emits
// one tile per sector ETF representing the whole sector, sized at the
// sum of the sector's true SP500 weight, so the layout still hints at
// market-cap proportions while clearly being a degraded view.
const SECTOR_ETF_TO_GICS = {
  XLK:  'Information Technology',
  XLV:  'Health Care',
  XLF:  'Financials',
  XLY:  'Consumer Discretionary',
  XLC:  'Communication Services',
  XLI:  'Industrials',
  XLP:  'Consumer Staples',
  XLE:  'Energy',
  XLU:  'Utilities',
  XLRE: 'Real Estate',
  XLB:  'Materials',
};

function isMarketHoursET() {
  const now = new Date();
  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone: 'America/New_York',
    hour12: false,
    weekday: 'short',
    hour: '2-digit',
    minute: '2-digit',
  }).formatToParts(now);
  const get = (t) => parts.find((p) => p.type === t)?.value;
  const wd = get('weekday');
  if (wd === 'Sat' || wd === 'Sun') return false;
  const h = Number(get('hour'));
  const m = Number(get('minute'));
  const minutes = h * 60 + m;
  // 09:30 → 16:00 ET. Pre-market (04:00) and post-market (16:00-20:00)
  // do trade on Massive's snapshot but with much thinner volume; we
  // treat them as off-hours from a cache-freshness perspective.
  return minutes >= 570 && minutes < 960;
}

function cacheControlHeader() {
  return isMarketHoursET()
    ? 'public, max-age=60, stale-while-revalidate=300'
    : 'public, max-age=900, stale-while-revalidate=86400';
}

// Returns the calendar date in America/New_York as YYYY-MM-DD. The
// trading-session date the function should anchor to is always the
// ET-local calendar date — the grouped endpoint's date param expects
// that, and "Friday's session" only makes sense in ET.
function etTodayIso() {
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: 'America/New_York',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).formatToParts(new Date());
  const get = (t) => parts.find((p) => p.type === t)?.value;
  return `${get('year')}-${get('month')}-${get('day')}`;
}

function subtractDaysIso(iso, n) {
  const d = new Date(`${iso}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() - n);
  return d.toISOString().slice(0, 10);
}

// Fetch one date's grouped daily bars (every US ticker, one record
// per ticker). Returns Map<symbol, {close, open, high, low, volume,
// barTime}> or null on failure. Massive's response is keyed by `T`
// (ticker), `c` (close), `o`, `h`, `l`, `v`, `t` (bar start ms).
async function fetchMassiveGroupedDay(dateIso) {
  if (!MASSIVE_API_KEY) return { ok: false, reason: 'no-key' };
  const url = `${MASSIVE_BASE}/v2/aggs/grouped/locale/us/market/stocks/${dateIso}?adjusted=true`;
  let res;
  try {
    res = await fetch(url, {
      headers: { Authorization: `Bearer ${MASSIVE_API_KEY}` },
      signal: AbortSignal.timeout(MASSIVE_TIMEOUT_MS),
    });
  } catch (err) {
    return { ok: false, reason: String(err?.name || 'fetch-error') };
  }
  if (!res.ok) {
    return { ok: false, reason: `http-${res.status}`, status: res.status };
  }
  let body;
  try {
    body = await res.json();
  } catch (err) {
    return { ok: false, reason: 'invalid-json' };
  }
  const list = Array.isArray(body?.results) ? body.results : [];
  if (list.length === 0) {
    // Non-trading day (weekend, holiday). Distinguishable from a
    // failed call because the HTTP status was 200 — the grouped
    // endpoint just has nothing to report for that calendar date.
    return { ok: true, empty: true, prices: new Map(), barTime: null };
  }
  const map = new Map();
  let mostRecentBar = 0;
  for (const r of list) {
    const sym = String(r?.T || '').toUpperCase();
    if (!sym) continue;
    const close = Number(r?.c);
    if (!Number.isFinite(close) || close <= 0) continue;
    map.set(sym, {
      close,
      open: Number(r?.o) || null,
      high: Number(r?.h) || null,
      low: Number(r?.l) || null,
      volume: Number(r?.v) || null,
    });
    const t = Number(r?.t) || 0;
    if (t > mostRecentBar) mostRecentBar = t;
  }
  return { ok: true, empty: false, prices: map, barTime: mostRecentBar || null };
}

// Find the two most-recent trading days with grouped data, walking
// backwards from today's ET calendar date. Two days are needed for
// the close-to-close percent-change calculation. The 8-day search
// ceiling covers any plausible weekend + multi-day holiday gap (the
// longest US market closure in modern history was the 4-session
// post-9/11 close, which fits in 6 days; 8 leaves slack).
async function fetchMassiveRecentTwoSessions() {
  const today = etTodayIso();
  const dates = [];
  for (let i = 0; i < 8; i++) dates.push(subtractDaysIso(today, i));
  const sessions = [];
  let lastReason = 'no-data-found';
  for (const d of dates) {
    if (sessions.length >= 2) break;
    const result = await fetchMassiveGroupedDay(d);
    if (!result.ok) {
      // Permanent error (auth / 5xx) — propagate up so the function
      // can fall back rather than fruitlessly walking back further.
      lastReason = result.reason;
      if (result.status && result.status >= 400 && result.status < 500) {
        return { ok: false, reason: result.reason, status: result.status };
      }
      continue;
    }
    if (result.empty) continue;
    sessions.push({ date: d, prices: result.prices, barTime: result.barTime });
  }
  if (sessions.length < 2) {
    return { ok: false, reason: `insufficient-sessions:${lastReason}` };
  }
  return { ok: true, last: sessions[0], prev: sessions[1] };
}

// Fallback path. Pulls the most recent two trading-day closes for each
// sector ETF in public.daily_eod and computes percent change. Returns
// 11 sector-level tiles with weight = sum of constituent SP500 weights
// per sector. The frontend renders the same treemap layout — just
// with 11 big tiles instead of 503 small ones — and shows a
// "degraded source" banner.
async function fetchSupabaseSectorEtfs() {
  if (!SUPABASE_URL || !SUPABASE_KEY) {
    return { ok: false, reason: 'no-supabase-config' };
  }
  const symbols = Object.keys(SECTOR_ETF_TO_GICS);
  // Pull the last 5 trading days per sector ETF — the math only needs
  // 2 closes but the buffer absorbs any single missing bar.
  const params = new URLSearchParams({
    select: 'symbol,trading_date,close',
    order: 'trading_date.desc,symbol.asc',
    symbol: `in.(${symbols.join(',')})`,
    limit: String(5 * symbols.length),
  });
  let res;
  try {
    res = await fetch(`${SUPABASE_URL}/rest/v1/daily_eod?${params}`, {
      headers: {
        apikey: SUPABASE_KEY,
        Authorization: `Bearer ${SUPABASE_KEY}`,
      },
      signal: AbortSignal.timeout(SUPABASE_TIMEOUT_MS),
    });
  } catch (err) {
    return { ok: false, reason: String(err?.name || 'fetch-error') };
  }
  if (!res.ok) return { ok: false, reason: `supabase-${res.status}` };
  const rows = await res.json().catch(() => null);
  if (!Array.isArray(rows) || rows.length === 0) {
    return { ok: false, reason: 'no-rows' };
  }
  // Bucket by symbol → ascending close array, take last two.
  const bySymbol = {};
  for (const r of rows) {
    (bySymbol[r.symbol] ||= []).push({ date: r.trading_date, close: Number(r.close) });
  }
  const map = new Map();
  let asOf = null;
  for (const sym of symbols) {
    const series = (bySymbol[sym] || []).sort((a, b) => a.date.localeCompare(b.date));
    if (series.length < 2) continue;
    const last = series[series.length - 1];
    const prev = series[series.length - 2];
    if (!last || !prev || !(prev.close > 0)) continue;
    map.set(sym, {
      last: last.close,
      prev: prev.close,
      pctChange: ((last.close - prev.close) / prev.close) * 100,
      asOf: last.date,
    });
    if (!asOf || last.date > asOf) asOf = last.date;
  }
  return { ok: true, prices: map, asOf };
}

export default async function handler(_request) {
  // Try Massive first. On any failure, fall back to the sector-ETF
  // overview from Supabase so the page still renders something useful.
  const massive = await fetchMassiveRecentTwoSessions();

  if (massive.ok) {
    const lastSession = massive.last;
    const prevSession = massive.prev;
    const tiles = [];
    let pricedCount = 0;
    for (const h of roster.holdings) {
      const lastPx = lastSession.prices.get(h.symbol);
      const prevPx = prevSession.prices.get(h.symbol);
      const last = lastPx?.close ?? null;
      const prev = prevPx?.close ?? null;
      const pctChange = (Number.isFinite(last) && Number.isFinite(prev) && prev > 0)
        ? ((last - prev) / prev) * 100
        : null;
      const tile = {
        symbol: h.symbol,
        name: h.name,
        sector: h.sector,
        weight: h.weight,
        last,
        prev,
        pctChange,
      };
      if (Number.isFinite(tile.pctChange)) pricedCount += 1;
      tiles.push(tile);
    }
    const payload = {
      mode: 'constituents',
      asOf: lastSession.date,
      prevSessionDate: prevSession.date,
      sourceUpdated: lastSession.barTime ? new Date(lastSession.barTime).toISOString() : null,
      source: 'massive',
      generatedAt: roster.generatedAt,
      count: tiles.length,
      pricedCount,
      tiles,
    };
    return jsonResponse(200, payload, cacheControlHeader());
  }

  // Massive unavailable. Try the sector-ETF fallback.
  const fallback = await fetchSupabaseSectorEtfs();
  if (!fallback.ok) {
    return jsonResponse(502, {
      error: 'No price source available',
      massive_failure: massive.reason,
      fallback_failure: fallback.reason,
    }, 'no-store');
  }

  // Sum SP500 weights per GICS sector to size the 11 fallback tiles by
  // true index weight rather than by ETF NAV.
  const weightBySector = {};
  for (const h of roster.holdings) {
    weightBySector[h.sector] = (weightBySector[h.sector] || 0) + h.weight;
  }

  const tiles = [];
  for (const [etf, sector] of Object.entries(SECTOR_ETF_TO_GICS)) {
    const px = fallback.prices.get(etf);
    if (!px) continue;
    tiles.push({
      symbol: etf,
      name: sector,
      sector,
      weight: weightBySector[sector] || 0,
      last: px.last,
      prev: px.prev,
      pctChange: px.pctChange,
    });
  }

  return jsonResponse(200, {
    mode: 'sector-etf-fallback',
    asOf: fallback.asOf,
    source: 'thetadata-via-supabase',
    generatedAt: roster.generatedAt,
    count: tiles.length,
    pricedCount: tiles.length,
    massiveFailure: massive.reason,
    tiles,
  }, cacheControlHeader());
}

function jsonResponse(status, body, cacheControl) {
  return new Response(JSON.stringify(round(body, 4)), {
    status,
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': cacheControl,
    },
  });
}

function round(node, decimals) {
  if (Array.isArray(node)) return node.map((n) => round(n, decimals));
  if (node && typeof node === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(node)) out[k] = round(v, decimals);
    return out;
  }
  if (typeof node === 'number') {
    const f = 10 ** decimals;
    return Math.round(node * f) / f;
  }
  return node;
}
