import '../src/styles/theme.css';
import '../src/styles/lab.css';
import ErrorBoundary from '../src/ErrorBoundary';
import Menu from '../src/components/Menu';
import TopNav from '../src/components/TopNav';
import SpxHeatmap from '../src/components/SpxHeatmap';

// SPX Heatmap lab. An equal-size GICS-sector grid of the top ~250
// single-name stocks by US options volume, colored by the most-recent
// session's percent change from previous close. Equal-size tiles are
// a deliberate departure from the conventional finviz / TradingView
// market-cap-weighted treemap: when MAG7 + a few mega-caps command a
// third of the visual, the other ~480 names compete for the
// remaining two-thirds and most of them aren't legible. Equal-size
// tiles give every name in the universe equal visual attention — the
// right call for an audience of vol traders who care about the names
// they actually trade, not the names that happen to be the largest
// by float-adjusted market cap.
//
// Data lineage:
//   tickers + sectors:  Barchart "stocks screener" CSV dropped at
//                       C:\sheets\, joined with GICS sectors via the
//                       GitHub datasets/s-and-p-500-companies CSV
//                       (SP500 names) plus a manually-maintained
//                       MANUAL_SECTORS map in the generator script
//                       for the ~90 non-SP500 names that show up on
//                       the options-active board (BTC miners, recent
//                       IPOs, ADRs, space / quantum / AI single
//                       names). Regenerated by
//                       scripts/backfill/options-volume-roster.mjs.
//   prices:             Massive grouped daily bars, two HTTP calls
//                       to fetch the most-recent two trading-day
//                       sessions, with ThetaData EOD via Supabase
//                       as a graceful fallback to 11 sector ETFs
//                       if Massive returns 401/403/timeout.
//
// See netlify/functions/heatmap.mjs for the join logic and
// src/components/SpxHeatmap.jsx for the equal-size grid renderer.
export default function App() {
  return (
    <div className="app-shell lab-shell heatmap-shell">
      <header className="lab-header">
        <div className="lab-brand">
          <span
            className="lab-badge"
            title="Heatmap · top by options volume, equal size, % change"
          >
            <span className="lab-badge__desktop-text">Heatmap</span>
            <span className="lab-badge__mobile-text">Heatmap</span>
          </span>
        </div>
        <TopNav />
        <a
          href="/"
          className="lab-home-button lab-home-button--inline lab-home-button--split"
          aria-label="Return Home"
        >
          <span className="lab-home-button__desktop-text">Home</span>
          <span className="lab-home-button__mobile-text">Home</span>
        </a>
        <Menu />
      </header>

      <section className="lab-slot heatmap-slot">
        <ErrorBoundary><SpxHeatmap /></ErrorBoundary>
      </section>

      <div className="card" style={{ padding: '1.1rem 1.25rem', margin: '1.25rem 0' }}>
        <div
          style={{
            fontFamily: "Calibri, 'Segoe UI', system-ui, sans-serif",
            fontSize: '0.7rem',
            letterSpacing: '0.14em',
            textTransform: 'uppercase',
            color: 'var(--text-secondary)',
            marginBottom: '0.45rem',
          }}
        >
          what this page measures
        </div>
        <div style={{ color: 'var(--text-secondary)', lineHeight: 1.65, fontSize: '0.95rem' }}>
          <p style={{ margin: '0 0 0.7rem' }}>
            The top ~250 single-name stocks by US options volume,
            rendered as equal-size tiles arranged into eleven GICS
            sector bands. Each tile is colored by the most-recent
            session's percent change from the previous close: strong
            red below -2%, neutral within ±0.25%, strong green above
            +2%, with linear ramps between. Hover any tile for the
            full company name, last price, previous close, and
            options volume rank.
          </p>
          <p style={{ margin: '0 0 0.7rem' }}>
            Equal-size tiles are a deliberate departure from the
            conventional finviz / TradingView market-cap-weighted
            treemap. When MAG7 + a handful of mega-caps command a
            third of the visual (NVDA + AAPL + MSFT + AMZN + AVGO +
            GOOGL/GOOG + META account for ~32% of SP500 weight), the
            other ~480 names compete for the remaining two-thirds and
            most of them are illegible. Equal-size tiles give every
            name in the universe equal visual attention. The right
            call for an audience that cares about the names they
            actually trade, not the names that happen to be the
            largest by float-adjusted market cap. The universe
            shrinks from ~503 SP500 members to the top ~250 single
            names by options volume in exchange.
          </p>
          <p style={{ margin: 0 }}>
            The constituent list comes from a Barchart "stocks
            screener" CSV pulled manually and dropped at C:\sheets\;
            the roster generator at
            scripts/backfill/options-volume-roster.mjs joins the
            list with GICS sector classifications (the GitHub
            datasets/s-and-p-500-companies CSV for SP500 names; a
            manually-maintained override map for the ~90 non-SP500
            names (recent IPOs, ADRs, BTC miners, space / quantum /
            AI single names) that the options-active board surfaces
            beyond the SP500). Live prices come from Massive's
            grouped daily bars endpoint, two HTTP calls per page
            load (most-recent trading day + the day before), edge-
            cached for 60 s during market hours and 15 minutes off-
            hours. When Massive returns an auth or 5xx error the
            page falls back to the eleven SPDR sector ETFs in
            ThetaData EOD as a degraded view.
          </p>
        </div>
      </div>

      <footer className="lab-footer">
        <span className="lab-footer-line">
          AI Gamma · SPX Heatmap · top by options volume, equal size · v0.2.0
        </span>
        <a href="/" className="lab-footer-home">Return Home</a>
      </footer>
    </div>
  );
}
